version: '2'
services:
    server:
        container_name: hello-world
        depends_on:
            - db
        build:
            context: .
            dockerfile: Dockerfile
        image: helloworld_api:latest
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
            - SPRING_DATASOURCE_USERNAME=compose-postgres
            - SPRING_DATASOURCE_PASSWORD=compose-postgres
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        ports:
            - 80:8080
        networks:
            - spring-cloud-network
    db:
        image: 'postgres:13.1-alpine'
        container_name: db
        environment:
            - POSTGRES_USER=compose-postgres
            - POSTGRES_PASSWORD=compose-postgres
        ports:
            - 5432:5432
        networks:
            - spring-cloud-network

networks:
    spring-cloud-network:
        driver: bridge