version: '3.9'

services:  
  server:
      container_name: fhir
      depends_on:
          - db
      build:
          context: FHIR
          dockerfile: Dockerfile
      image: fhir-container:latest
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dbuser    
        - SPRING_DATASOURCE_USERNAME=dbuser
        - SPRING_DATASOURCE_PASSWORD=dbuser
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      ports:
        - 8080:8080

  db:
      image: 'postgres:13.1-alpine'
      container_name: db
      environment:
          - POSTGRES_USER=dbuser
          - POSTGRES_PASSWORD=dbuser
      volumes:
        - "./init.sql:/tmp/init.sql"
        - "./database:/var/lib/postgresql/data"
networks:
  default:
    name: kong-net

